name = "ruinabla"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

[pages_build_config]
build_command = "npm run build"
destination = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ruinabla-db"
database_id = "9605e55c-fb4a-40b2-947f-736e9f91eea0"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ruinabla-content"
